// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybdfjsofgzzmwlyxdmba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliZGZqc29mZ3p6bXdseXhkbWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NjQ2NzEsImV4cCI6MjA2NjA0MDY3MX0.oQsZ9X6C3fQ_lX_DILTWKUNNdrvejLZ10WBmGVpWLCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);