// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtywigqqsdpljtozvwnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10eXdpZ3Fxc2RwbGp0b3p2d25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTIxODYsImV4cCI6MjA2NDAyODE4Nn0.z9xmibqDgJuEf3maFk4ZikuQF_OJmTdqCbnCC4Np8L0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);